#!/bin/bash
#
##########################
#			 #
# SysInfo para Intrusión #
#			 #
##########################
#
#
#Desarrollado por ShadowVMX para tratar de vulnerar aún más el sistema una vez estemos dentro.
#
#

#Trap del ctrl_c


trap exitSys SIGINT

exitSys(){
	echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Saliendo, espere..."
	sleep 1.5
	exit
}


echo "$(tput setaf 153)"; figlet sysinfo 
echo " "
echo "$(tput setaf 112)                 @ShadowVMX v1.4"
echo " "
echo "$(tput setaf 8) "

#Información del Kernel

echo " "
echo "___________________________________________________"
echo "___________________________________________________"
echo " "

echo -n "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Script ejecutado por --> $(tput setaf 3)" && whoami && echo "$(tput setaf 8)"

echo "___________________________________________________"
echo " "
echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Kernel Version: "
echo "$(tput setaf 2) "
uname -a
echo " "
uname -r
echo " "
echo "$(tput setaf 8) "

#Información acerca de la CPU
sleep 1.5

echo "___________________________________________________"
echo " "
echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]CPU Model & CPU Speed: "
echo "$(tput setaf 2) "
lscpu | grep "Model name:"
echo " "
inxi | grep "CPU:"
echo " "
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Información acerca de la SHELL Actual
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Variables de entorno: "
echo "$(tput setaf 2) "
env 2>/dev/null | grep -v 'LS_COLORS' 2>/dev/null
echo " "
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Información sobre variables y carpetas de ejecución
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Variables de entorno complementarias: "
echo "$(tput setaf 2) "
echo $PATH
echo " "
ls -ld 2> /dev/null $(echo $PATH | tr ":" " ")
echo " "
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "


#Memoria usada por los discos duros
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Memoria usada (HDD|SSD): "
echo "$(tput setaf 2) "
inxi | grep "Storage: " | cut -d " " -f1,2,3,4,5
echo " "
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Información de la memoria RAM
sleep 1.5


echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Memoria RAM: "
echo "$(tput setaf 2) "
free -h
echo " "
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Servicios actuales activos
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Servicios actuales levantados: "
echo "$(tput setaf 2) "
service --status-all | grep "+"
echo " "
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Capabilities actuales en el sistema
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Capabilities: "
echo "$(tput setaf 2) "
getcap -r / 2> /dev/null 
echo " "
echo "--> GTFOBins (https://gtfobins.github.io/)"
echo " "
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Permisos SUID
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Permisos SUID: "
echo "$(tput setaf 2)"
find . / -perm /4000 2> /dev/null
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Permisos GUID
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Permisos GUID: "
echo "$(tput setaf 2)"
find . / -perm /2000 2> /dev/null
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Grupos con el ID
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]ID (grupos): "
echo "$(tput setaf 2)"
id
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Permisos en ejecución con sudo -l
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Permisos de ejecución del usuario actual: "
echo "$(tput setaf 2)"
sudo -l
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Leer el /etc/passwd
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Acceso al /etc/passwd: "
echo "$(tput setaf 2)"
cat /etc/passwd
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Leer el /etc/shadow
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Acceso al /etc/shadow: "
echo "$(tput setaf 2)"
cat /etc/shadow &> /dev/null 

if [[ $? == 1 ]] ; then
	echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]No podemos leer /etc/shadow"
else
	cat /etc/shadow
fi
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Leer el directorio de root
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Acceso al directorio de root: "
echo "$(tput setaf 2)"
lsd -la /root/ 2> /dev/null

if [[ $? == 1 ]] ; then
	echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]No tenemos permiso para acceder."
else
	lsd -la /root/ 
fi
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Visualizar las conexiones TCP
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Listando las conexiones TCP: "
echo "$(tput setaf 2)"
ss -t
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Visualizar las conexiones UDP
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Listando las conexiones UDP: "
echo "$(tput setaf 2)"
ss -ua
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Visualizar los procesos actuales en el sistema
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Listando los procesos actuales en el sistema: "
echo "$(tput setaf 2)"
ps aux
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Visualizar la característica ARP
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]ARP: "
echo "$(tput setaf 2)"
arp
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Información de Networking
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Direcciones IP en el sistema: "
echo "$(tput setaf 2)"
ifconfig
echo " "
echo " "
ip a 
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "


#Usuarios conectados actualmente
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Usuarios conectados actualmente al sistema: "
echo "$(tput setaf 2)"
w
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Se permite el login de root por SSH
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Conexión vía SSH: "
echo "$(tput setaf 2)"

cat /etc/ssh/sshd_config | grep "PermitRootLogin yes" &> /dev/null

if [[ $? == 0 ]] ; then
	echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Conexión posible --> [PermitRootLogin Yes]"
else
	echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Conexión no posible --> [PermitRootLogin No]"
fi
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Shells disponibles en el sistema
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Shells disponibles: "
echo "$(tput setaf 2)"
cat /etc/shells
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Información acerca de las contraseñas del sistema
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Información acerca de las contraseñas: "
echo "$(tput setaf 2)"
cat /etc/login.defs | grep "^PASS_MAX_DAYS\|^PASS_MIN_DAYS\|^PASS_WARN_AGE\|^ENCRYPT_METHOD"
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "


#Información acerca de las tareas cron
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Información acerca de las tareas cron: "
echo "$(tput setaf 2)"
lsd -ll /etc/cron.d/
echo " "
echo " "
cat /etc/crontab 
echo " "
echo " "
lsd -ll /etc/cron.daily/
echo " "
echo " "
lsd -al /var/spool/cron/crontabs/
echo " "
echo " "
lsd -al /etc/cron.hourly/
echo " "
echo " "
lsd -al /etc/cron.monthly/
echo " "
echo " "
lsd -al /etc/cron.weekly/
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Versión de los distintos componentes (sudo)
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Versión del sudo: "
echo "$(tput setaf 2)"
sudo -V | grep "version"
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Versión de apache2
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Versión de apache2: "
echo "$(tput setaf 2)"
apache2 -v
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#MySQL version
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Versión de MySQL: "
echo "$(tput setaf 2)"

ls -l /usr/bin/mysql &> /dev/null

if [[ $? == 0 ]] ; then
	mysql --version
else
	echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]MySQL no está instalado en el sistema"
fi
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Softwares interesantes
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Softwares críticos e importantes: "
echo "$(tput setaf 2)"
which nc 2> /dev/null
which netcat 2> /dev/null
which nmap 2> /dev/null
which gcc 2> /dev/null
which curl 2> /dev/null
which python 2> /dev/null
which python2.7 2> /dev/null
which python3 2> /dev/null
which wget 2> /dev/null
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Posibilidad de leer historial
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Historial del usuario: "
echo "$(tput setaf 2)"
ls -la ~/.*_history 2>/dev/null
echo " "
echo " "
echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Historial de root: "
echo "$(tput setaf 2)"

ls -la /root/.*_history &>/dev/null

if [[ $? == 0 ]] ; then
	ls -la /root/.*_history
else
	echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Inaccesible."
fi
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "

#Archivos de Dockers
sleep 1.5

echo "$(tput setaf 6)[$(tput setaf 1)*$(tput setaf 6)]Archivos de Dockers: "
echo "$(tput setaf 2)"
find / . -iname "docker*" 2> /dev/null
echo "$(tput setaf 8) "
echo "___________________________________________________"
echo " "
echo " "
echo "$(tput setaf 3)[$(tput setaf 1)*$(tput setaf 3)]$(tput setaf 6)Completado"
echo " "
